
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 23 23:48:18 CET 2022
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUMERO = 37;
  public static final int DOSPUNTOS = 14;
  public static final int FUNCTION = 21;
  public static final int MULT = 3;
  public static final int PUNTOYCOMA = 13;
  public static final int INTEGER = 23;
  public static final int OUT = 26;
  public static final int MINUS = 2;
  public static final int IDENTIFICADOR = 36;
  public static final int IS = 24;
  public static final int AND = 6;
  public static final int RECORD = 29;
  public static final int TYPE = 33;
  public static final int BEGIN = 15;
  public static final int PUT_LINE = 28;
  public static final int LOOP = 25;
  public static final int ASSIGN = 7;
  public static final int IF = 22;
  public static final int CPARENTESIS = 11;
  public static final int EOF = 0;
  public static final int BOOLEAN = 16;
  public static final int RETURN = 30;
  public static final int COMILLAS = 9;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int CADENA = 35;
  public static final int APARENTESIS = 10;
  public static final int NEQ = 5;
  public static final int CONSTANT = 17;
  public static final int ELSE = 18;
  public static final int ACCESS = 8;
  public static final int WHILE = 34;
  public static final int THEN = 32;
  public static final int END = 19;
  public static final int FALSE = 20;
  public static final int GT = 4;
  public static final int PROCEDURE = 27;
}

